### ISSUE TITLE
Use package engines to tell tonic to use node v6

### ISSUE THREAD

**Issue by tolmasky** [andrewthehan/etude.js#1]
If you set your engines field in the package.json to { node: ">=6" } then Tonic will automatically select 6 as the default node version (and you won't have to tell people to set it themselves).

**Comment by andrewthehan** [comment]
I was wondering how to do this. Thanks for the info.

**Comment by tolmasky** [comment]
Didn't see this, but its actually "engines" not "engine": https://docs.npmjs.com/files/package.json

**Comment by andrewthehan** [comment]
Yeah I just made the fix. Not sure how to test this besides publishing a new version... Still waiting for Tonic to sync the changes.

**Comment by andrewthehan** [comment]
Yup, it's working now. Thanks again!
